development:
  adapter: postgresql
  database: aulaleve
  host: 192.168.0.110
  port: 5433
  user: ruby
  password: test123
  pool: 5

production:
  adapter: postgresql
  database: <%= ENV["DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5