Estado.create(:sigla => 'AC', :nome => "Acre")
Estado.create(:sigla => 'AL', :nome => "Alagoas")
Estado.create(:sigla => 'AM', :nome => "Amazonas")
Estado.create(:sigla => 'AP', :nome => "Amapá")
Estado.create(:sigla => 'BA', :nome => "Bahia")
Estado.create(:sigla => 'CE', :nome => "Ceará")
Estado.create(:sigla => 'DF', :nome => "Distrito Federal")
Estado.create(:sigla => 'ES', :nome => "Espírito Santo")
Estado.create(:sigla => 'GO', :nome => "Goiás")
Estado.create(:sigla => 'MA', :nome => "Maranhão")
Estado.create(:sigla => 'MG', :nome => "Minas Gerais")
Estado.create(:sigla => 'MS', :nome => "Mato Grosso do Sul")
Estado.create(:sigla => 'MT', :nome => "Mato Grosso")
Estado.create(:sigla => 'PA', :nome => "Pará")
Estado.create(:sigla => 'PB', :nome => "Paraíba")
Estado.create(:sigla => 'PE', :nome => "Pernambuco")
Estado.create(:sigla => 'PI', :nome => "Piauí")
Estado.create(:sigla => 'PR', :nome => "Paraná")
Estado.create(:sigla => 'RJ', :nome => "Rio de Janeiro")
Estado.create(:sigla => 'RN', :nome => "Rio Grande do Norte")
Estado.create(:sigla => 'RO', :nome => "Rondônia")
Estado.create(:sigla => 'RR', :nome => "Roraima")
Estado.create(:sigla => 'RS', :nome => "Rio Grande do Sul")
Estado.create(:sigla => 'SC', :nome => "Santa Catarina")
Estado.create(:sigla => 'SE', :nome => "Sergipe")
Estado.create(:sigla => 'SP', :nome => "São Paulo")
Estado.create(:sigla => 'TO', :nome => "Tocantins")

TypesInstitution.create(:code => 'private_intuition',          :title => 'Particular')
TypesInstitution.create(:code => 'state_public_intuition',     :title => 'Pública - Estadual')
TypesInstitution.create(:code => 'municipal_public_intuition', :title => 'Pública - Municipal')
TypesInstitution.create(:code => 'federal_public_intuition',   :title => 'Pública - Federal')


VideoTutorials.create(:code => 'tutorial_1', :title => 'Video 1', :video_url => "https://www.youtube.com/watch?v=FBRLBHoKTVw")
VideoTutorials.create(:code => 'tutorial_2', :title => 'Video 2', :video_url => "https://www.youtube.com/watch?v=kxkPF59FPVU")
VideoTutorials.create(:code => 'tutorial_3', :title => 'Video 3', :video_url => "https://www.youtube.com/watch?v=le6RQdDfSdE")
VideoTutorials.create(:code => 'tutorial_4', :title => 'Video 4', :video_url => "https://www.youtube.com/watch?v=RyiM3uD3JBc")
VideoTutorials.create(:code => 'tutorial_5', :title => 'Video 5', :video_url => "https://www.youtube.com/watch?v=2zwwNMT-cV0")
VideoTutorials.create(:code => 'tutorial_6', :title => 'Video 6', :video_url => "https://www.youtube.com/watch?v=az3wGuzcghc")